name: base
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - pip=20.1.1
  - matplotlib=3.3.0
  - voila=0.2.4
  - bqplot=0.12.15
  - parallel=20200922
  - pip:
      - ipyfetch==0.1.3
      - voila-material==0.3.0
      - pyprojroot==0.2.0
      - jupytext==1.6.0
      - httpie==2.3.0
      - ipykernel==5.3.4
      - xlrd==1.2.0
      - ipympl==0.5.8
      - jupyterlab-templates==0.2.5
      - black==19.10b0
